// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using PostMessageExp.Models.WebView;
using UIKit;

namespace PostMessageExp.iOS
{
	public partial class StartViewController : UIViewController
	{
		public StartViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			
			
		}


		public override async void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue(segue, sender);

			if (segue.Identifier == "goToWeb")
			{
				var dcv = segue.DestinationViewController as WkViewController;
				CustomWebviewManager manager = new CustomWebviewManager();

				//string url = await manager.GetConfigurations(chiaveServizio: "chiave", codiceFornitura: "codice fornitura");
			}
		}
	}
}
