// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using PostMessageExp.Models.WebView;
using UIKit;
using WebKit;

namespace PostMessageExp.iOS
{
  public partial class WkViewController : UIViewController, CustomWebviewInterface
  {
    private const string jsonStringToSend = "{\"employees\": [{ \"firstName\":\"John\", \"lastName\":\"Doe\" }, { \"firstName\":\"Anna\" , \"lastName\":\"Smith\" },{ \"firstName\": \"Peter\" , \"lastName\": \"Jones \" }]}";

    private WKWebView wkWebview;

    public string url;

    public WkViewController(IntPtr handle) : base(handle)
    {
    }

    public override async void ViewDidLoad()
    {
      base.ViewDidLoad();

      var scriptDelegate = new WkPostMessageScriptMessageHandler();

      WKUserContentController contentController = new WKUserContentController();
      contentController.AddScriptMessageHandler(scriptDelegate, "sendToApp");
      contentController.AddScriptMessageHandler(scriptDelegate, "onHtmlLoadCompleted");

      WKWebViewConfiguration config = new WKWebViewConfiguration();
      config.UserContentController = contentController;

      wkWebview = new WKWebView(webViewContainer.Frame, config);
      webViewContainer.AddSubview(wkWebview);

      var wkUIDelegate = new PostMessageWkWebViewDelegate();
      wkUIDelegate.parentController = this;
      wkWebview.UIDelegate = wkUIDelegate;
      
      var navigationDelegate = new PostMessageNavigationDelegate();
      wkWebview.NavigationDelegate = navigationDelegate;

      //LoadHtml();
      
      await SetManager();
    }

    private async Task SetManager()
    {
		  CustomWebviewManager manager = new CustomWebviewManager();
      manager.SetIntInstance(this);
      manager.GetConfigurations(chiaveServizio: "chaive servizio", codiceFornitura: "codice fornitura");
    }

    private void LoadHtml()
    {
      string fileName = "PosteMessage/index"; // remember case-sensitive
      string localHtmlUrl = NSBundle.MainBundle.PathForResource(fileName, "html");

      string remoteUrl = string.IsNullOrEmpty(this.url) ? "http://www.digitalentitypreview.com/mobileapp/enel/enelenergia/R3/DEMO/postMessageIndex.html" : this.url;
      var url = new NSUrl(localHtmlUrl, false);
      
      var url2 = new NSUrl(remoteUrl);
      wkWebview.LoadRequest(new NSUrlRequest(url));
    }

    partial void buttonAction(UIButton sender)
    {
      this.EvaluateJavascript("non usato per ora");
    }

    public void ShowLoader(bool IsVisible, int timeout)
    {
      
    }

    public void ShowThankYouPage( /*ThankYouModel model*/)
    {
      
    }

    public void EvaluateJavascript(String command)
    {
      wkWebview.EvaluateJavaScript(string.Format("sendToWebviewContainer('{0}');", jsonStringToSend), null);
    }

    public void InitWebView(ConfigurationWebView command)
    {
      this.url = command.URL;
      LoadHtml();
    }
  }

  public class PostMessageWkWebViewDelegate : WKUIDelegate
  {
    public UIViewController parentController;

    public override void RunJavaScriptAlertPanel(WKWebView webView, string message, WKFrameInfo frame, Action completionHandler)
    {
      var alert = UIAlertController.Create("Alert", message, UIAlertControllerStyle.Alert);
      alert.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

      //Let javascript handle the OK click by passing the completionHandler to the controller
      parentController.PresentViewController(alert, true, completionHandler);
    }
  }

  public class WkPostMessageScriptMessageHandler : WKScriptMessageHandler
  {
    
    
    public override void DidReceiveScriptMessage(WKUserContentController userContentController, WKScriptMessage message)
    {
      if (message.Name == "sendToApp")
      {
        var arguments = message.Body;
        System.Diagnostics.Debug.WriteLine("Contenuto arrivato " + arguments);
      }
      else if (message.Name == "onHtmlLoadCompleted")
      {
        System.Diagnostics.Debug.WriteLine("pagina caricata");
      }
    }
  }

  public class PostMessageNavigationDelegate : WKNavigationDelegate
  {
    public override void DidFinishNavigation(WKWebView webView, WKNavigation navigation)
    {
      System.Diagnostics.Debug.WriteLine("Web view page has been loaded");
    }
  }
}
