// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;
using WebKit;

namespace PostMessageExp.iOS
{
  public partial class WkViewController : UIViewController
  {
    private const string jsonStringToSend = "{\"employees\": [{ \"firstName\":\"John\", \"lastName\":\"Doe\" }, { \"firstName\":\"Anna\" , \"lastName\":\"Smith\" },{ \"firstName\": \"Peter\" , \"lastName\": \"Jones \" }]}";

    private WKWebView wkWebview;

    public WkViewController(IntPtr handle) : base(handle)
    {
    }

    public override void ViewDidLoad()
    {
      base.ViewDidLoad();

      var scriptDelegate = new WkPostMessageScriptMessageHandler();

      WKUserContentController contentController = new WKUserContentController();
      contentController.AddScriptMessageHandler(scriptDelegate, "functionCallForNativeCode");

      WKWebViewConfiguration config = new WKWebViewConfiguration();
      config.UserContentController = contentController;

      wkWebview = new WKWebView(webViewContainer.Frame, config);
      webViewContainer.AddSubview(wkWebview);

      var wkUIDelegate = new PostMessageWkWebViewDelegate();
      wkUIDelegate.parentController = this;
      wkWebview.UIDelegate = wkUIDelegate;

      LoadHtml();
    }

    private void LoadHtml()
    {
      string fileName = "PosteMessage/index"; // remember case-sensitive
      string localHtmlUrl = NSBundle.MainBundle.PathForResource(fileName, "html");
      var url = new NSUrl(localHtmlUrl, false);
      wkWebview.LoadRequest(new NSUrlRequest(url));
    }


    partial void buttonAction(UIButton sender)
    {
      wkWebview.EvaluateJavaScript(string.Format("PostMessageForAlert('{0}');", jsonStringToSend), null);
    }
  }

  public class PostMessageWkWebViewDelegate : WKUIDelegate
  {
    public UIViewController parentController;

    public override void RunJavaScriptAlertPanel(WKWebView webView, string message, WKFrameInfo frame, Action completionHandler)
    {
      var alert = UIAlertController.Create("Alert", message, UIAlertControllerStyle.Alert);
      alert.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));

      //Let javascript handle the OK click by passing the completionHandler to the controller
      parentController.PresentViewController(alert, true, completionHandler);
    }
  }

  public class WkPostMessageScriptMessageHandler : WKScriptMessageHandler
  {
    public override void DidReceiveScriptMessage(WKUserContentController userContentController, WKScriptMessage message)
    {
      if (message.Name == "functionCallForNativeCode")
      {
        var arguments = message.Body;
        System.Diagnostics.Debug.WriteLine("Contenuto arrivato " + arguments);
      }
    }
  }
}